name: Deploy to Render

on:
  push:
    branches:
      - try  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Render
        run: |
          curl -fsSL https://install.render.com | bash
          export PATH=$HOME/.render/bin:$PATH
          render login --api-key rnd_I4LH4MoJ1ycdycZLRNVV10FUF6SO

      - name: Build Docker image
        run: docker build -t coursesmp:latest .

      - name: Push & Deploy to Render
        run: |
          # If migrations needed in future, uncomment the next line
          # docker run --rm coursesmp:latest python manage.py migrate
          render deploy --service srv-d4jojqfdiees73b1tneg --api-key rnd_I4LH4MoJ1ycdycZLRNVV10FUF6SO
