name: Deploy Django to Render

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Render Docker Registry
        run: |
          echo "Logging into Render..."
          docker login registry.render.com -u coursesmp -p rnd_I4LH4MoJ1ycdycZLRNVV10FUF6SO

      - name: Build Docker image
        run: |
          docker build -t registry.render.com/coursesmp:latest .

      - name: Push Docker image to Render
        run: |
          docker push registry.render.com/coursesmp:latest

      - name: Trigger Render deploy
        run: |
          curl -X POST \
          -H "Authorization: Bearer rnd_I4LH4MoJ1ycdycZLRNVV10FUF6SO" \
          https://api.render.com/deploy/srv-d4jmchvdiees738t3ie0
