name: Deploy Django to Render with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Render CLI and add to PATH
      - name: Install Render CLI
        run: |
          curl -L https://install.render.com | bash
          export PATH=$PATH:$HOME/.render/bin

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t coursesmp .

      # 4. Deploy to Render
      - name: Deploy to Render
        run: |
          $HOME/.render/bin/render deploy --service coursesmp --api-key rnd_I4LH4MoJ1ycdycZLRNVV10FUF6SO
