name: Deploy Django to Render with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Render CLI
        run: |
          curl -L https://install.render.com | bash

      - name: Build Docker image
        run: |
          docker build -t coursesmp .

      - name: Deploy to Render
        run: |
          render deploy --service coursesmp --api-key rnd_I4LH4MoJ1ycdycZLRNVV10FUF6SO
